@MyResumeSite.Server_HostAddress = http://localhost:5269

###
GET {{MyResumeSite.Server_HostAddress}}/getskills/
Accept: application/json
###
GET {{MyResumeSite.Server_HostAddress}}/gethobbies/
Accept: application/json